name: sous-project
recipe: drupal8
config:
  webroot: web
  php: '7.3'
services:
  appserver:
    run:
      - composer install
tooling:
  drush:
    service: appserver
    env:
      DRUSH_OPTIONS_URI: "https://sous-project.lndo.site"
